apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "cache"
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:9119
  - name: redisPassword
    value: ""